// react-demo/src/components/UserCard.tsx
import React from 'react';
import './UserCard.css';

interface UserCardProps {
  name: string;
  role: string;
  initials?: string;
  onMessageUser: (name: string) => void;
}

export const UserCard: React.FC<UserCardProps> = ({
  name,
  role,
  initials = 'U',
  onMessageUser
}) => {
  return (
    <div className="user-card">
      <div className="avatar">{initials}</div>
      <div className="info">
        <h4>{name}</h4>
        <p>{role}</p>
      </div>
      <button className="btn-sm" onClick={() => onMessageUser(name)}>Message</button>
    </div>
  );
};
export default UserCard;

// angular-demo/src/app/pages-components/user-card/user-card.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-user-card',
  standalone: true,
  templateUrl: './user-card.component.html',
  styleUrl: './user-card.component.css'
})
export class UserCardComponent {
  // Inputs: Data passed DOWN from the page to this component
  name = input.required<string>();
  role = input.required<string>();
  initials = input<string>('U');

  // Output: Events passed UP from this component to the page
  messageUser = output<string>();
}

<div class="user-card">
  <div class="avatar">{{ initials() }}</div>
  <div class="info">
    <h4>{{ name() }}</h4>
    <p>{{ role() }}</p>
  </div>
  <button class="btn-sm" (click)="messageUser.emit(name())">Message</button>
</div>
